using System.Globalization;
using Avalonia;

namespace BoxPilot.App.Services;

public sealed record LanguageOption(string Code, string DisplayName);

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AppName"] = "BoxPilot",
            ["AboutBoxPilot"] = "About BoxPilot…",
            ["AboutTitle"] = "About BoxPilot",
            ["MenuSettings"] = "Settings…",
            ["OpenBoxPilot"] = "Open BoxPilot",
            ["Close"] = "Close",
            ["NavDashboard"] = "Dashboard",
            ["NavProfiles"] = "Profiles",
            ["NavConfiguration"] = "Configuration",
            ["NavLogs"] = "Live logs",
            ["NavTools"] = "Toolbox",
            ["NavSettings"] = "Settings",
            ["Core"] = "sing-box core",
            ["CoreOnline"] = "Core online",
            ["CoreOffline"] = "Core offline",
            ["Start"] = "Start",
            ["Stop"] = "Stop",
            ["Restart"] = "Restart",
            ["Status"] = "Status",
            ["ActiveProfile"] = "Active profile",
            ["NoProfile"] = "No profile selected",
            ["ProxyNodes"] = "Proxy nodes",
            ["PolicyGroups"] = "Policy groups",
            ["SearchNodes"] = "Search nodes",
            ["TestAll"] = "Test all",
            ["SortByLatency"] = "Sort by latency",
            ["NoProxyGroups"] = "No selectable policy groups",
            ["NoMatchingNodes"] = "No matching nodes",
            ["NodeSelected"] = "Selected",
            ["DelayTestComplete"] = "{0} of {1} nodes responded",
            ["Refresh"] = "Refresh",
            ["Latency"] = "Latency",
            ["Version"] = "Version",
            ["MixedProxy"] = "Mixed proxy",
            ["Enabled"] = "Enabled",
            ["Disabled"] = "Disabled",
            ["Starting"] = "Starting",
            ["Running"] = "Running",
            ["Stopping"] = "Stopping",
            ["Stopped"] = "Stopped",
            ["Faulted"] = "Faulted",
            ["Upload"] = "Upload",
            ["Download"] = "Download",
            ["RefreshSubscription"] = "Refresh subscription",
            ["ProfilesTitle"] = "Profiles & subscriptions",
            ["ImportSection"] = "Add a source",
            ["ProfileLibrary"] = "Profile library",
            ["DeleteProfileQuestion"] = "Delete this profile?",
            ["DeleteProfileHint"] = "Its local configuration and unsaved draft will be removed.",
            ["Cancel"] = "Cancel",
            ["ConfirmDelete"] = "Delete profile",
            ["SubscriptionName"] = "Profile name",
            ["SubscriptionUrl"] = "Subscription URL",
            ["Import"] = "Import subscription",
            ["CreateBlank"] = "Create blank profile",
            ["Update"] = "Update",
            ["Delete"] = "Delete",
            ["Nodes"] = "nodes",
            ["ManualProfile"] = "Manual profile",
            ["ConfigurationTitle"] = "Configuration editor",
            ["UnsavedChanges"] = "Unsaved changes",
            ["ChangesSaved"] = "All changes saved",
            ["SaveChangesBeforeUpdate"] = "Save or discard configuration changes before updating the subscription.",
            ["ConfigurationValid"] = "Configuration is valid",
            ["RestartToApply"] = "Saved. Restart the connection to apply these changes.",
            ["Save"] = "Save",
            ["Format"] = "Format",
            ["Validate"] = "Validate",
            ["JsonPlaceholder"] = "Select a profile to edit its sing-box JSON.",
            ["LogsTitle"] = "Live core logs",
            ["LiveOutput"] = "LIVE OUTPUT",
            ["Clear"] = "Clear",
            ["AutoScroll"] = "Auto scroll",
            ["ToolsTitle"] = "sing-box toolbox",
            ["CommandPresets"] = "QUICK COMMANDS",
            ["Command"] = "Command arguments",
            ["RunCommand"] = "Run command",
            ["CommandHint"] = "Example: generate rand --hex 32",
            ["CommandOutput"] = "Command output",
            ["SettingsTitle"] = "Application settings",
            ["Appearance"] = "Appearance",
            ["Theme"] = "Theme",
            ["Language"] = "Language",
            ["System"] = "System",
            ["Light"] = "Light",
            ["Dark"] = "Dark",
            ["CoreSettings"] = "Core & networking",
            ["CorePath"] = "sing-box executable",
            ["MixedPort"] = "Mixed proxy port",
            ["ApiPort"] = "Clash API port",
            ["SystemProxy"] = "Set the operating-system proxy while running",
            ["TunMode"] = "Enable TUN mode",
            ["NetworkChangesHint"] = "The first TUN start uses BoxPilot TUN to install a protected system service with one administrator approval.",
            ["ServiceAuthorizationDenied"] = "BoxPilot TUN needs administrator approval to install the system service.",
            ["ServiceInstallationFailed"] = "The protected TUN service could not be installed.",
            ["ServiceRemovalFailed"] = "The protected TUN service could not be removed.",
            ["ServiceUnavailable"] = "The protected TUN service is unavailable. Try enabling TUN again to repair it.",
            ["ServiceDisconnected"] = "The protected TUN service disconnected and the connection was stopped.",
            ["RemoveTunService"] = "Remove TUN service",
            ["TunServiceRemoved"] = "TUN service removed",
            ["LaunchSettings"] = "Launch behavior",
            ["StartOnLaunch"] = "Start core when BoxPilot opens",
            ["CloseToTray"] = "Keep running when the main window closes",
            ["SaveSettings"] = "Save settings",
            ["SettingsSaved"] = "Settings saved",
            ["DataDirectory"] = "Open data directory",
            ["Quit"] = "Quit",
            ["Subscription"] = "Subscription",
            ["SubscriptionNamePlaceholder"] = "My subscription",
            ["ConfigurationValidationLabel"] = "JSON",
            ["Timeout"] = "Timeout",
            ["Warnings"] = "warnings",
            ["CoreNotFound"] = "Not found",
            ["CoreNotFoundHelp"] = "sing-box was not found. Choose its executable in Settings.",
            ["InvalidSubscriptionUrl"] = "The subscription URL is invalid.",
            ["ProcessExited"] = "Process exited with code {0}.",
            ["SubscriptionCurrent"] = "Subscription is already up to date",
            ["ExitSuccess"] = "Command completed",
            ["ExitCode"] = "Command exited with code {0}",
            ["Ready"] = "Ready",
            ["Working"] = "Working…",
        };

    private static readonly IReadOnlyDictionary<string, string> SimplifiedChinese =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AppName"] = "BoxPilot",
            ["AboutBoxPilot"] = "关于 BoxPilot…",
            ["AboutTitle"] = "关于 BoxPilot",
            ["MenuSettings"] = "设置…",
            ["OpenBoxPilot"] = "打开 BoxPilot",
            ["Close"] = "关闭",
            ["NavDashboard"] = "仪表盘",
            ["NavProfiles"] = "配置与订阅",
            ["NavConfiguration"] = "配置编辑器",
            ["NavLogs"] = "实时日志",
            ["NavTools"] = "工具箱",
            ["NavSettings"] = "设置",
            ["Core"] = "sing-box 内核",
            ["CoreOnline"] = "内核运行中",
            ["CoreOffline"] = "内核已停止",
            ["Start"] = "启动",
            ["Stop"] = "停止",
            ["Restart"] = "重启",
            ["Status"] = "运行状态",
            ["ActiveProfile"] = "当前配置",
            ["NoProfile"] = "尚未选择配置",
            ["ProxyNodes"] = "代理节点",
            ["PolicyGroups"] = "策略组",
            ["SearchNodes"] = "搜索节点",
            ["TestAll"] = "全部测速",
            ["SortByLatency"] = "按延迟排序",
            ["NoProxyGroups"] = "暂无可切换的策略组",
            ["NoMatchingNodes"] = "没有匹配的节点",
            ["NodeSelected"] = "已切换",
            ["DelayTestComplete"] = "{0}/{1} 个节点可用",
            ["Refresh"] = "刷新",
            ["Latency"] = "延迟测试",
            ["Version"] = "版本",
            ["MixedProxy"] = "混合代理",
            ["Enabled"] = "已启用",
            ["Disabled"] = "未启用",
            ["Starting"] = "正在启动",
            ["Running"] = "运行中",
            ["Stopping"] = "正在停止",
            ["Stopped"] = "已停止",
            ["Faulted"] = "异常",
            ["Upload"] = "上传速度",
            ["Download"] = "下载速度",
            ["RefreshSubscription"] = "更新订阅",
            ["ProfilesTitle"] = "配置与订阅",
            ["ImportSection"] = "添加来源",
            ["ProfileLibrary"] = "配置库",
            ["DeleteProfileQuestion"] = "要删除这个配置吗？",
            ["DeleteProfileHint"] = "本地配置和未保存的草稿都会被移除。",
            ["Cancel"] = "取消",
            ["ConfirmDelete"] = "删除配置",
            ["SubscriptionName"] = "配置名称",
            ["SubscriptionUrl"] = "订阅地址",
            ["Import"] = "导入订阅",
            ["CreateBlank"] = "新建空白配置",
            ["Update"] = "更新",
            ["Delete"] = "删除",
            ["Nodes"] = "个节点",
            ["ManualProfile"] = "手动配置",
            ["ConfigurationTitle"] = "配置编辑器",
            ["UnsavedChanges"] = "有未保存的修改",
            ["ChangesSaved"] = "修改已全部保存",
            ["SaveChangesBeforeUpdate"] = "请先保存或放弃配置修改，再更新订阅。",
            ["ConfigurationValid"] = "配置验证通过",
            ["RestartToApply"] = "配置已保存，重启连接后生效。",
            ["Save"] = "保存",
            ["Format"] = "格式化",
            ["Validate"] = "验证配置",
            ["JsonPlaceholder"] = "请选择一个配置以编辑 sing-box JSON。",
            ["LogsTitle"] = "内核实时日志",
            ["LiveOutput"] = "实时输出",
            ["Clear"] = "清空",
            ["AutoScroll"] = "自动滚动",
            ["ToolsTitle"] = "sing-box 工具箱",
            ["CommandPresets"] = "快捷命令",
            ["Command"] = "命令参数",
            ["RunCommand"] = "运行命令",
            ["CommandHint"] = "示例：generate rand --hex 32",
            ["CommandOutput"] = "命令输出",
            ["SettingsTitle"] = "应用设置",
            ["Appearance"] = "外观",
            ["Theme"] = "主题",
            ["Language"] = "界面语言",
            ["System"] = "跟随系统",
            ["Light"] = "浅色",
            ["Dark"] = "深色",
            ["CoreSettings"] = "内核与网络",
            ["CorePath"] = "sing-box 可执行文件",
            ["MixedPort"] = "混合代理端口",
            ["ApiPort"] = "Clash API 端口",
            ["SystemProxy"] = "运行时自动设置系统代理",
            ["TunMode"] = "启用 TUN 模式",
            ["NetworkChangesHint"] = "首次启动 TUN 时，BoxPilot TUN 会安装受保护的系统服务，并仅请求一次管理员授权。",
            ["ServiceAuthorizationDenied"] = "BoxPilot TUN 需要管理员授权才能安装系统服务。",
            ["ServiceInstallationFailed"] = "无法安装受保护的 TUN 系统服务。",
            ["ServiceRemovalFailed"] = "无法移除受保护的 TUN 系统服务。",
            ["ServiceUnavailable"] = "TUN 系统服务当前不可用，请再次启用 TUN 以修复。",
            ["ServiceDisconnected"] = "TUN 系统服务已断开，连接已安全停止。",
            ["RemoveTunService"] = "移除 TUN 系统服务",
            ["TunServiceRemoved"] = "TUN 系统服务已移除",
            ["LaunchSettings"] = "启动行为",
            ["StartOnLaunch"] = "BoxPilot 启动时运行内核",
            ["CloseToTray"] = "关闭主窗口后继续在后台运行",
            ["SaveSettings"] = "保存设置",
            ["SettingsSaved"] = "设置已保存",
            ["DataDirectory"] = "打开数据目录",
            ["Quit"] = "退出",
            ["Subscription"] = "订阅",
            ["SubscriptionNamePlaceholder"] = "我的订阅",
            ["ConfigurationValidationLabel"] = "JSON",
            ["Timeout"] = "超时",
            ["Warnings"] = "条警告",
            ["CoreNotFound"] = "未找到",
            ["CoreNotFoundHelp"] = "未找到 sing-box，请在设置中选择内核可执行文件。",
            ["InvalidSubscriptionUrl"] = "订阅地址无效。",
            ["ProcessExited"] = "进程退出，状态码为 {0}。",
            ["SubscriptionCurrent"] = "订阅已经是最新版本",
            ["ExitSuccess"] = "命令执行完成",
            ["ExitCode"] = "命令退出，状态码为 {0}",
            ["Ready"] = "就绪",
            ["Working"] = "处理中…",
        };

    private IReadOnlyDictionary<string, string> current = SimplifiedChinese;

    public event Action? LanguageChanged;

    public IReadOnlyList<LanguageOption> Languages { get; } =
    [
        new("zh-CN", "简体中文"),
        new("en-US", "English"),
    ];

    public string CurrentLanguage { get; private set; } = "zh-CN";

    public string this[string key] => current.GetValueOrDefault(key, key);

    public void Apply(string? language)
    {
        CurrentLanguage = string.Equals(language, "en-US", StringComparison.OrdinalIgnoreCase)
            ? "en-US"
            : "zh-CN";
        current = CurrentLanguage == "en-US" ? English : SimplifiedChinese;

        var culture = CultureInfo.GetCultureInfo(CurrentLanguage);
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;

        if (Application.Current?.Resources is { } resources)
        {
            foreach (var pair in current)
                resources[pair.Key] = pair.Value;
        }

        LanguageChanged?.Invoke();
    }
}
